version: 2
project_name: tedge-oscar
builds:
  - id: tedge-oscar
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
      - riscv64
      - mips
      - mips64
    goarm:
      - "5"
      - "6"
      - "7"
    goriscv64:
      - rva22u64
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    ids: [tedge-oscar]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - sm-plugins/tedge-flows
      - sm-plugins/tedge-flow-image

release:
  mode: keep-existing

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: deb
    ids: [tedge-oscar]
    formats:
      - deb
    priority: optional
    maintainer: "tedge-oscar maintainers <tedge-oscar@thin-edge.io>"
    description: "CLI for managing thin-edge.io flows and OCI images."
    vendor: "thin-edge.io"
    homepage: "https://github.com/thin-edge/tedge-oscar"
    license: "Apache-2.0"
    bindir: /usr/bin
    scripts:
      postinstall: packaging/postinstall.sh
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/tedge-oscar/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/tedge-oscar/README.md
      - src: ./sm-plugins/flow
        dst: /etc/tedge/sm-plugins/flow
        file_info:
          mode: 0755
      - src: ./sm-plugins/tedge-flows
        dst: /etc/tedge/sm-plugins/tedge-flows
        file_info:
          mode: 0755
      - src: ./sm-plugins/tedge-flow-image
        dst: /etc/tedge/sm-plugins/tedge-flow-image
        file_info:
          mode: 0755
      - src: internal/config/tedge-oscar-linux.toml
        dst: /etc/tedge/plugins/tedge-oscar.toml
        file_info:
          mode: 0644
      - src: packaging/completions/_zsh
        dst: /usr/share/zsh/vendor-completions/_tedge-oscar
        file_info:
          mode: 0644
      - src: packaging/completions/_bash
        dst: /usr/share/bash-completion/completions/tedge-oscar
        file_info:
          mode: 0644
  - id: rpm
    ids: [tedge-oscar]
    formats:
      - rpm
    priority: optional
    maintainer: "tedge-oscar maintainers <tedge-oscar@thin-edge.io>"
    description: "CLI for managing thin-edge.io flows and OCI images."
    vendor: "thin-edge.io"
    homepage: "https://github.com/thin-edge/tedge-oscar"
    license: "Apache-2.0"
    bindir: /usr/bin
    scripts:
      postinstall: packaging/postinstall.sh
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/tedge-oscar/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/tedge-oscar/README.md
      - src: ./sm-plugins/flow
        dst: /etc/tedge/sm-plugins/flow
        file_info:
          mode: 0755
      - src: ./sm-plugins/tedge-flows
        dst: /etc/tedge/sm-plugins/tedge-flows
        file_info:
          mode: 0755
      - src: ./sm-plugins/tedge-flow-image
        dst: /etc/tedge/sm-plugins/tedge-flow-image
        file_info:
          mode: 0755
      - src: internal/config/tedge-oscar-linux.toml
        dst: /etc/tedge/plugins/tedge-oscar.toml
        file_info:
          mode: 0644
      - src: packaging/completions/_zsh
        dst: /usr/share/zsh/vendor-completions/_tedge-oscar
        file_info:
          mode: 0644
      - src: packaging/completions/_bash
        dst: /usr/share/bash-completion/completions/tedge-oscar
        file_info:
          mode: 0644
  - id: apk
    ids: [tedge-oscar]
    formats:
      - apk
    priority: optional
    maintainer: "tedge-oscar maintainers <tedge-oscar@thin-edge.io>"
    description: "CLI for managing thin-edge.io flows and OCI images."
    vendor: "thin-edge.io"
    homepage: "https://github.com/thin-edge/tedge-oscar"
    license: "Apache-2.0"
    bindir: /usr/bin
    scripts:
      postinstall: packaging/postinstall.sh
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/tedge-oscar/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/tedge-oscar/README.md
      - src: ./sm-plugins/flow
        dst: /etc/tedge/sm-plugins/flow
        file_info:
          mode: 0755
      - src: ./sm-plugins/tedge-flows
        dst: /etc/tedge/sm-plugins/tedge-flows
        file_info:
          mode: 0755
      - src: ./sm-plugins/tedge-flow-image
        dst: /etc/tedge/sm-plugins/tedge-flow-image
        file_info:
          mode: 0755
      - src: internal/config/tedge-oscar-linux.toml
        dst: /etc/tedge/plugins/tedge-oscar.toml
        file_info:
          mode: 0644
      - src: packaging/completions/_zsh
        dst: /usr/share/zsh/vendor-completions/_tedge-oscar
        file_info:
          mode: 0644
      - src: packaging/completions/_bash
        dst: /usr/share/bash-completion/completions/tedge-oscar
        file_info:
          mode: 0644
